### ISSUE TITLE
Moving to official ANTLR 4 grammars

### ISSUE THREAD

**Issue by KvanTTT** [developeron29/PLSQLParser#2]
What do you think about moving your grammar to official [ANTLR Grammars repo](https://github.com/antlr/grammars-v4)?

**Comment by developeron29** [comment]
Yep, Sounds good.
How should i go about doing that?

**Comment by KvanTTT** [comment]
Just make fork, add grammar files and pull request after that :)

**Comment by developeron29** [comment]
Yep,  I guess that was a silly question.
Thanks!
